#!/usr/bin/env bash
# Configuring Ubuntu server:
#   - localhost resolves from 127.0.0.1 to  127.0.0.2
#   - facebook.com resolves from 157.240.11.35 to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
